# Site settings
title: Adventures of Dominik
description: A place to keep all the stuff I've worked on
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dominik Roje
user_description: I'm a person who likes to do things. I'll get around to this later... Maybe.
user_title: Software Developer
email: dom.roje@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
